linters-settings:
  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 10

  goconst:
    min-len: 3
    min-occurrences: 3

  golint:
    min-confidence: 0.8

  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  enable:
    - errcheck
    - govet
    - goconst
    - golint
    - staticcheck
    - gosec
    - ineffassign
    - deadcode
    - unused
    - unconvert
    - misspell
    - whitespace

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-use-default: false
  exclude:
    - "error return value not checked.*"

run:
  timeout: 5m
  skip-dirs:
    - migrations
  skip-files:
    - ".*_test.go"
